# fly.toml app configuration file generated for clen3t-white-fog-5060 on 2025-07-11T23:24:18+12:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'clen3t-white-fog-5060'
primary_region = 'syd'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
